### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by dausruddin** [Xposed-Modules-Repo/cn.kwaiching.hook#6]
Hi. I have updated the module, but now the app won't open. 
This is the log

```
[ 2023-03-06T21:43:26.185    10169: 18054: 18054 I/LSPosed-Bridge  ] Loading module cn.kwaiching.hook from /data/app/~~88KIIZTYQUKKyc8qbW23Eg==/cn.kwaiching.hook-uLtG-rfYg7i_iV3Bv-vM2A==/base.apk
[ 2023-03-06T21:43:26.209    10169: 18054: 18054 I/LSPosed-Bridge  ]   Loading class cn.kwaiching.hook.hook.ChingHook
[ 2023-03-06T21:43:26.214    10169: 18054: 18054 I/LSPosed-Bridge  ]   Loading class cn.kwaiching.hook.hook.Ching
[ 2023-03-06T21:43:26.295    10169: 18054: 18054 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.UnsatisfiedLinkError: dlopen failed: library "libkwaiching.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at O000O0O0OO0OO0O0OO0.O000O0O00OO0O0OOO0O.<clinit>(Unknown Source:10)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(Unknown Source:0)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1339)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3538)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by kwaiching** [comment]
Download the version on https://u062.com/d/16731109-40183208-4b8931  for your Android ABI
